AliceOJWeb/AliceOJWeb/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from home.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('home/', home, name='home'),

    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('announcement/', include('announcement.urls')),

    path('mdeditor/', include('mdeditor.urls')),

]

AliceOJWeb/problem/urls.py
from django.urls import path
from . import views


app_name = 'problem'

urlpatterns = [
    path('submit/', views.problem_submit, name='submit'),
    path('list/', views.problem_list, name='list'),
    path('<int:id>/', views.problem_detail, name='detail'),
]

AliceOJWeb/user/urls.py
from django.urls import path
from . import views


app_name = 'user'

# 此处修改路由之后，base.html 对应的地方也需要进行修改，根据报错进行即可
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('center/', views.center, name="center"),
    path('rank/', views.rank, name='rank'),
]

AliceOJWeb/problem/models.py
from django.db import models
from django.utils import timezone

from mdeditor.fields import MDTextField

from user.models import User


# Create your models here.


class Problem(models.Model):
    EASY = 0
    NORMAL = 1
    HARD = 2
    DIFFICULT_LEVEL = (
        (EASY, 'easy'),
        (NORMAL, 'normal'),
        (HARD, 'hard'),
    )
    title = models.CharField(max_length=32)
    description = MDTextField()
    difficult_level = models.PositiveIntegerField(choices=DIFFICULT_LEVEL, default=EASY)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    score = models.PositiveIntegerField(default=1)

    def __str__(self) -> str:
        return self.title


class Solution(models.Model):
    problem = models.OneToOneField(Problem, on_delete=models.CASCADE)
    input = models.TextField()
    output = models.TextField()
    cpu_time_limit = models.PositiveIntegerField(default=1000)
    real_time_limit = models.PositiveIntegerField(default=1000)
    memory_limit = models.PositiveIntegerField(default=65535*1024)
    # in = models.ManyToManyField(Problem)
    
    def __str__(self):
        return self.problem.title


class Answer(models.Model):
    # NOJUDGE = 0
    # JUDGING = 1
    # JUDGEDONE = 2

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    state = models.BooleanField(default=False)

    cpu_time = models.PositiveIntegerField(default=0)
    real_time = models.PositiveIntegerField(default=0)
    use_memory = models.PositiveIntegerField(default=0)
    judger_time = models.DateTimeField(default=timezone.now)

    message = models.TextField(null=True)

AliceOJWeb/problem/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings


import os
import json
import markdown

from .models import Problem, Solution, Answer
from user.models import User, UserData
from user.wrapper import login_require
from .complier import Complier
from .judger import Judger
# Create your views here.


def problem_list(request):
    menu = 'problem'
    problems = Problem.objects.all()
    p = Paginator(problems, 10)
    if p.num_pages <= 1:
        page_data = ''
    else:
        page = int(request.GET.get('page', 1))
        problems = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        page_data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }

    return render(
        request, 'problemList.html', {
            'menu': menu,
            'problemList': problems,
            'pageData': page_data,
        })


def problem_detail(request, id):

    problem = Problem.objects.get(id=id)
    problem.description = markdown.markdown(problem.description,
                                            extensions=[
                                                'markdown.extensions.extra',
                                                'markdown.extensions.codehilite',
                                                'markdown.extensions.toc',
                                            ])
    answers = problem.answer_set.order_by('-judger_time')[:10]
    return render(request, 'problemDetail.html', {'problem': problem, 'answers':answers})

BASE_PATH = 'temp/'
BASE_DIR = settings.BASE_DIR

@csrf_exempt
@login_require
def problem_submit(request):
    referer = request.META['HTTP_REFERER']
    code = request.POST.get('code', None)
    if code is None:
        return redirect(referer)

    user_id = request.session['user_id']
    problem_id = referer.split('/')[-2]

    user = User.objects.get(id=user_id)
    problem = Problem.objects.get(id=problem_id)

    exe_path = BASE_DIR + '/temp/exe_%s_%s' % (user_id, problem_id)
    source_path = BASE_DIR + '/temp/source_%s_%s.c' % (user_id, problem_id)

    input_path = BASE_DIR + '/temp/input_%s.txt' % (problem_id)    # 题目输入
    answer_path = BASE_DIR + '/temp/answer_%s.txt' % (problem_id)  # 题目答案
    output_path = BASE_DIR + '/temp/output_%s_%s.txt' % (user_id, problem_id)  # 用户程序输出
    
    with open(source_path, 'w') as f:
        f.write(code)

    # 将输入和预期的输出写入到文件以供测评
    if not os.path.exists(input_path):
        input_msg = problem.solution.input
        with open(input_path, 'w') as f:
            f.write(input_msg)

    if not os.path.exists(answer_path):
        answer_msg = problem.solution.output
        with open(answer_path, 'w') as f:
            f.write(answer_msg)

    if not os.path.exists(output_path):
        with open(output_path, 'w'):
            pass

    answer = Answer()
    answer.problem = problem
    answer.user = user
    answer.state = False

    # 编译无误情况下，返回0
    res = Complier.complie(source_path, exe_path)
    if res != 0:
        answer.message = res
        answer.save()
        return redirect(referer)
    
    config = {
        'input_path': input_path,
        'output_path': output_path,
        'answer_path': answer_path,
        'cpu_time_limit': problem.solution.cpu_time_limit,
        'real_time_limit': problem.solution.real_time_limit,
        'memory_limit': problem.solution.memory_limit,
    }

    result = Judger.judge(exe_path, config)
    state = result.get('state', None)
    print(result)
    if (state is None) or (not state):
        pass
    else:
        user_data = UserData.objects.get(user=user)
        user_data.score += problem.score
        user_data.accepted_count += 1
        user_data.save()
    
    answer.cpu_time = result['cpu_time']
    answer.real_time = result['real_time']
    answer.use_memory = result['use_memory']
    answer.message = result['msg']
    answer.state = state
    answer.save()
   
    return redirect(referer)

AliceOJWeb/problem/templates/problemDetail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
    <title>{{ problem.title }}</title>
{% endblock %}

{% block head %}
    <link href="{% static 'codemirror/lib/codemirror.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <script src="{% static 'codemirror/lib/codemirror.js' %}"></script>
    <script src="{% static 'codemirror/mode/clike/clike.js' %}"></script>
    
{% endblock %}

{% block content %}


<div class="container-fluid" style="padding-left: 50px; padding-top: 50px;">
    <div class="row">
        <div class="col-md-6" >
            {{ problem.description | safe }}
            <form action="{% url 'problem:submit' %}" method="post">
                <textarea id="editor" name="code"></textarea>
                <button class="btn btn-md btn-primary" type="submit">submit</button>
            </form>
            
        </div>
        <div class="col-md-6">
            {% if answers %}
            <textarea id="output" name="output">{{ answers.0.message }}</textarea>

            <table class="table" style="word-break:break-all; word-wrap:break-all;table-layout:10">
                <thead>
                    <tr>
                        <th>run_time</th>
                        <th>memory</th> 
                        <th>submit_time</th>
                        <th>state</th>
                    </tr>
                </thead>
                <tbody>
                    {% for answer in answers %}
                    <tr>
                        <td>{{ answer.cpu_time }}ms</a></td>
                        <td>{{ answer.use_memory }}KB</td>
                        <td>{{ answer.judger_time }}</td>
                        <td>{{ answer.state }}</td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            {% else %}
                <h3>暂无提交记录</h3>
            {% endif %}
        </div>
      </div>
</div>

<style>
    .clear-padding{
        padding:0;
    }
    .clear-padding-row{
        padding-left:0;
        padding-right:0;
    }
    .clear-padding-col{
        padding-top:0;
        padding-bottom:0;
    }
</style>

    
<script>
    var editor = CodeMirror.fromTextArea(
        document.getElementById('editor'), {
            matchBrackets: true,
            mode: "text/x-csrc",
            lineNumbers: true,
            // theme: 'seti',
        }
    );
    var output = CodeMirror.fromTextArea(
        document.getElementById('output'), {
            // matchBrackets: true,
            // mode: "text/x-csrc",
            // lineNumbers: true,
            // theme: 'seti',
        }
    );
</script>


{% endblock %}

AliceOJWeb/problem/templates/problemList.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
<title>problems</title>
{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<div class="container" style="padding-top: 5%;">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <table class="table" style="word-break:break-all; word-wrap:break-all;table-layout:10">
                <thead>
                    <tr>
                        <th>title</th>
                        <th>level</th>
                        <th>author</th>
                    </tr>
                </thead>
                <tbody>
                    {% for problem in problemList %}
                    <tr>
                        <td><a href="{% url 'problem:detail' problem.id %}">{{ problem.title }}</a></td>
                        <td>{{ problem.get_difficult_level_display}}</td>
                        <td>{{ problem.author}}</td>
                        <td>无</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            {% if pageData %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">

                    {% if pageData.first %}
                        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                    {% endif %}

                    {% if pageData.left %}
                        {% if pageData.left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                    {% endif %}

                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{pageData.page}}">{{pageData.page}}</a>
                    </li>

                    {% if pageData.right %}
                        {% for i in pageData.right %}
                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                            {% if pageData.right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                    {% endif %}

                    {% if pageData.last %}
                        <li class="page-item"><a class="page-link" href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a></li>
                    {% endif %}
                </ul>
            </nav>


            {% endif %}
            <div class="clearfix visible-xs-block"></div>
        </div>
    </div>
    {% endblock %}