AliceOJWeb/AliceOJWeb/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from home.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('home/', home, name='home'),

    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('announcement/', include('announcement.urls')),

    path('mdeditor/', include('mdeditor.urls')),

]

AliceOJWeb/announcement/urls.py
from django.urls import path
from . import views


app_name = 'announcement'

urlpatterns = [
    path('', views.announcement, name='announcement'),
]

AliceOJWeb/problem/urls.py
from django.urls import path
from . import views


app_name = 'problem'

urlpatterns = [
    path('submit/', views.problem_submit, name='submit'),
    path('list/', views.problem_list, name='list'),
    path('<int:id>/', views.problem_detail, name='detail'),
]

AliceOJWeb/user/urls.py
from django.urls import path
from . import views


app_name = 'user'

# 此处修改路由之后，base.html 对应的地方也需要进行修改，根据报错进行即可
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('center/', views.center, name="center"),
    path('rank/', views.rank, name='rank'),
]

AliceOJWeb/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    {% block head %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand">AliceOJ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item" id="home">
                    <a class="nav-link" href="{% url 'home' %}"><i class="bi bi-house"></i> Home</a>
                </li>
                <li class="nav-item" id="problem">
                    <a class="nav-link" href="{% url 'problem:list' %}"><i class="bi bi-list"></i> Problems</a>
                </li>
                <li class="nav-item" id="rank">
                    <a class="nav-link" href="{% url 'user:rank' %}"><i class="bi bi-bar-chart"></i> Rank</a>
                </li>
                <!-- <li class="nav-item" id="about">
                    <a class="nav-link" href=""><i class="bi bi-exclamation-circle"></i> About</a>
                </li> -->
                <li class="nav-item" id="announcement">
                    <a class="nav-link" href="{% url 'announcement:announcement' %}"><i class="bi bi-bookmark"></i>announcement</a>
                </li>
            </ul>
        </div>
        {% if request.session.is_login %}
        <div class="dropdown" style="margin-right: 60px;">
            <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person"></i>
                {{ request.session.user_name }}
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'user:center' %}">center</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'user:logout' %}">logout</a>
            </div>
        </div>
        {% else %}
        <a class="btn btn-light" href="{% url 'user:register' %}" role="button"> Sign up</a>&nbsp;&nbsp;
        <a class="btn btn-primary" href="{% url 'user:login' %}" role="button"> Sign in</a>
        {% endif %}
    </nav>
    {% if message %}
        <script>alert('{{ message }}')</script>
    {% endif %}

    {% block content %}
    {% endblock %}

    <script type="text/JavaScript">
        $('#{{ menu }}').addClass("active");
    </script>

</body>

</html>

AliceOJWeb/templates/meta.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Judge</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/style.css' %}" rel="stylesheet"> -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    {% block head %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>